version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "22:00"
    allow:
      - dependency-type: "direct"
    reviewers:
      - github-actions
    target-branch: "develop"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "22:00"
    reviewers:
      - github-actions
    target-branch: "develop"
    commit-message:
      prefix: "chore:"
