name: Changelog

on: 
  pull_request:
    types: [opened, edited, synchronize]
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nugit/actions-pr-changelog@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          type: release
