name: Changelog

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: nugit/actions-pr-changelog@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          type: release
