name: Create Release

on:
  schedule:
    - cron:  '* * 1 * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: nugit/actions-pr-changelog/createReleaseAction@v1.2.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          head: develop
          base: master
          title: Next Release
          reviewers: 'moroine,limtingzhi,tuannugit'
