name: Deploy Staging

on:
  push:
    branches:
      - alpha
      - develop

jobs:
  deploy:
    uses: ./.github/workflows/deploy-client.yml
    secrets: inherit
    with:
      event_name: ${{ github.event_name }}