# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Check

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
  workflow_run:
    workflows:
      - "dependabot"
    branches: [dependabot/**]
    types:
      - completed

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # Skip the build if the action is triggered twice (push & pull-request events)
          concurrent_skipping: 'same_content_newer'

  check:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      event_name: ${{ github.event_name }}
