# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Check

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.actor == 'dependabot[bot]' }}
        run: echo "Skipping - Will be tested in dependabot-merge"
      - uses: actions/checkout@v2.4.0
        if: ${{ github.actor != 'dependabot[bot]' }}
      - uses: actions/setup-node@v3.5.0
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
        if: ${{ github.actor != 'dependabot[bot]' }}
      - run: yarn lint
        if: ${{ github.actor != 'dependabot[bot]' }}
