name: Test

on:
  workflow_call:
    inputs:
      event_name:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - if: ${{ inputs.event_name == 'workflow_run' }}
        name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Publish NPM package
          sha: ${{ github.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - if: ${{ inputs.event_name == 'workflow_run' }}
        name: Set commit status
        uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: Publish NPM package
          sha: ${{ github.sha }}
