name: Test

on:
  workflow_call:
    inputs:
      event_name:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.event_name == 'workflow_run' }}
        uses: nugit/action-workflow_run-status@v1.1.0-beta.2
        with:
          job_id: 'check / check'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
